### ISSUE TITLE
Remove analysis file from 480km_2stream

### ISSUE THREAD

**Issue by junmeiban** [JCSDA-internal/mpas-jedi-data#2]
## Description
According to the issue https://github.com/JCSDA-internal/mpas-jedi/issues/624 and PR https://github.com/JCSDA-internal/mpas-jedi/pull/626, ```analysis.2018-04-15_00.00.00.nc``` should be removed from the directory ```testinput_tier_1/480km_2stream/```

## Requirements

Remove ```analysis.2018-04-15_00.00.00.nc``` from the directory ```testinput_tier_1/480km_2stream/```

## Dependencies
Waiting on the following PR:
 - Waiting on https://github.com/JCSDA-internal/mpas-jedi/pull/626

**Comment by jjguerrette** [comment]
Closed by #3
